[build]
command = "hugo --gc --minify"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV           = "production"
HUGO_VERSION       = "0.146.4"
NODE_VERSION       = "v23.11.0"
NPM_VERSION        = "10.9.2"

[context.split1]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --enableGitInfo"

    [context.split1.environment]
    HUGO_ENV     = "production"
    HUGO_VERSION = "0.146.4"
    NODE_VERSION = "v23.11.0"
    NPM_VERSION  = "10.9.2"

[context.deploy-preview]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"

    [context.deploy-preview.environment]
    HUGO_VERSION = "0.146.4"
    NODE_VERSION = "v23.11.0"
    NPM_VERSION  = "10.9.2"

[context.branch-deploy]
command = "hugo mod tidy && hugo mod npm pack && npm install && hugo --gc --minify -b $DEPLOY_PRIME_URL"

    [context.branch-deploy.environment]
    HUGO_VERSION = "0.146.4"
    NODE_VERSION = "v23.11.0"
    NPM_VERSION  = "10.9.2"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

# Security Headers
[[headers]]
  for = "/*"
  [headers.values]
    # Content Security Policy - Optimized for Hugo static site with local assets
    Content-Security-Policy = "default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self'; connect-src 'self'; media-src 'self'; object-src 'none'; child-src 'none'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'; manifest-src 'self';"
    
    # Prevent clickjacking attacks - deny all framing for security
    X-Frame-Options = "DENY"
    
    # Prevent MIME type sniffing
    X-Content-Type-Options = "nosniff"
    
    # Control referrer information - balanced privacy and functionality
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Control browser features and APIs - minimal permissions for portfolio site
    Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=(), usb=(), vr=(), accelerometer=(), gyroscope=(), magnetometer=(), clipboard-read=(), clipboard-write=(), fullscreen=(self)"
    
    # Additional security headers
    X-XSS-Protection = "1; mode=block"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"